package com.project2.ism.Model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "franchise_settlement_batch")
public class FranchiseSettlementBatch {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "franchise_id", nullable = false)
    private Long franchiseId;

    @Column(name = "cycle_key", nullable = false)
    private String cycleKey;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private BatchStatus status = BatchStatus.DRAFT;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "total_merchants")
    private Integer totalMerchants = 0;

    @Column(name = "completed_merchants")
    private Integer completedMerchants = 0;

    @Column(name = "failed_merchants")
    private Integer failedMerchants = 0;

    @Column(name = "total_transactions")
    private Integer totalTransactions = 0;

    @Column(name = "processed_transactions")
    private Integer processedTransactions = 0;

    @Column(name = "total_franchise_commission", precision = 19, scale = 2)
    private BigDecimal totalFranchiseCommission = BigDecimal.ZERO;

    @Column(name = "processing_started_at")
    private LocalDateTime processingStartedAt;

    @Column(name = "processing_completed_at")
    private LocalDateTime processingCompletedAt;

    @Column(name = "error_message", length = 1000)
    private String errorMessage;

    public enum BatchStatus {
        DRAFT, PROCESSING, COMPLETED, PARTIALLY_COMPLETED, FAILED, CANCELLED
    }

    public FranchiseSettlementBatch() {
    }

    public FranchiseSettlementBatch(Long franchiseId, String cycleKey, String createdBy) {
        this.franchiseId = franchiseId;
        this.cycleKey = cycleKey;
        this.createdBy = createdBy;
        this.status = BatchStatus.DRAFT;
        this.createdAt = LocalDateTime.now();
    }

    // Getters and setters will be generated by IntelliJ

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFranchiseId() {
        return franchiseId;
    }

    public void setFranchiseId(Long franchiseId) {
        this.franchiseId = franchiseId;
    }

    public String getCycleKey() {
        return cycleKey;
    }

    public void setCycleKey(String cycleKey) {
        this.cycleKey = cycleKey;
    }

    public BatchStatus getStatus() {
        return status;
    }

    public void setStatus(BatchStatus status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Integer getTotalMerchants() {
        return totalMerchants;
    }

    public void setTotalMerchants(Integer totalMerchants) {
        this.totalMerchants = totalMerchants;
    }

    public Integer getCompletedMerchants() {
        return completedMerchants;
    }

    public void setCompletedMerchants(Integer completedMerchants) {
        this.completedMerchants = completedMerchants;
    }

    public Integer getFailedMerchants() {
        return failedMerchants;
    }

    public void setFailedMerchants(Integer failedMerchants) {
        this.failedMerchants = failedMerchants;
    }

    public Integer getTotalTransactions() {
        return totalTransactions;
    }

    public void setTotalTransactions(Integer totalTransactions) {
        this.totalTransactions = totalTransactions;
    }

    public Integer getProcessedTransactions() {
        return processedTransactions;
    }

    public void setProcessedTransactions(Integer processedTransactions) {
        this.processedTransactions = processedTransactions;
    }

    public BigDecimal getTotalFranchiseCommission() {
        return totalFranchiseCommission;
    }

    public void setTotalFranchiseCommission(BigDecimal totalFranchiseCommission) {
        this.totalFranchiseCommission = totalFranchiseCommission;
    }

    public LocalDateTime getProcessingStartedAt() {
        return processingStartedAt;
    }

    public void setProcessingStartedAt(LocalDateTime processingStartedAt) {
        this.processingStartedAt = processingStartedAt;
    }

    public LocalDateTime getProcessingCompletedAt() {
        return processingCompletedAt;
    }

    public void setProcessingCompletedAt(LocalDateTime processingCompletedAt) {
        this.processingCompletedAt = processingCompletedAt;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}