package com.project2.ism.Model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "franchise_batch_merchant")
public class FranchiseBatchMerchant {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "franchise_batch_id", nullable = false)
    private Long franchiseBatchId;

    @Column(name = "merchant_id", nullable = false)
    private Long merchantId;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private MerchantProcessingStatus status = MerchantProcessingStatus.SELECTED;

    @Column(name = "processing_started_at")
    private LocalDateTime processingStartedAt;

    @Column(name = "processing_completed_at")
    private LocalDateTime processingCompletedAt;

    @Column(name = "processed_count")
    private Integer processedCount = 0;

    @Column(name = "failed_count")
    private Integer failedCount = 0;

    @Column(name = "total_amount", precision = 19, scale = 2)
    private BigDecimal totalAmount = BigDecimal.ZERO;

    @Column(name = "error_message", length = 500)
    private String errorMessage;

    public enum MerchantProcessingStatus {
        SELECTED, PROCESSING, COMPLETED, FAILED
    }

    public FranchiseBatchMerchant() {
    }

    public FranchiseBatchMerchant(Long franchiseBatchId, Long merchantId) {
        this.franchiseBatchId = franchiseBatchId;
        this.merchantId = merchantId;
        this.status = MerchantProcessingStatus.SELECTED;
    }

    // Getters and setters will be generated by IntelliJ

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFranchiseBatchId() {
        return franchiseBatchId;
    }

    public void setFranchiseBatchId(Long franchiseBatchId) {
        this.franchiseBatchId = franchiseBatchId;
    }

    public Long getMerchantId() {
        return merchantId;
    }

    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    public MerchantProcessingStatus getStatus() {
        return status;
    }

    public void setStatus(MerchantProcessingStatus status) {
        this.status = status;
    }

    public LocalDateTime getProcessingStartedAt() {
        return processingStartedAt;
    }

    public void setProcessingStartedAt(LocalDateTime processingStartedAt) {
        this.processingStartedAt = processingStartedAt;
    }

    public LocalDateTime getProcessingCompletedAt() {
        return processingCompletedAt;
    }

    public void setProcessingCompletedAt(LocalDateTime processingCompletedAt) {
        this.processingCompletedAt = processingCompletedAt;
    }

    public Integer getProcessedCount() {
        return processedCount;
    }

    public void setProcessedCount(Integer processedCount) {
        this.processedCount = processedCount;
    }

    public Integer getFailedCount() {
        return failedCount;
    }

    public void setFailedCount(Integer failedCount) {
        this.failedCount = failedCount;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}