//package com.project2.ism.Model;
//
//import jakarta.persistence.*;
//import java.math.BigDecimal;
//import java.time.LocalDateTime;
//
//@Entity
//@Table(name = "settlement_batch_candidates")
//public class SettlementBatchCandidate {
//
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    private Long id;
//
//    @Column(name = "batch_id", nullable = false)
//    private Long batchId;
//
//    @Column(name = "vendor_tx_id", nullable = false)
//    private String vendorTxId;
//
//    @Column(name = "expected_amount", precision = 19, scale = 2)
//    private BigDecimal expectedAmount;
//
//    @Column(name = "expected_fee", precision = 19, scale = 2)
//    private BigDecimal expectedFee;
//
//    @Column(name = "expected_net", precision = 19, scale = 2)
//    private BigDecimal expectedNet;
//
//    @Column(name = "selected_at")
//    private LocalDateTime selectedAt = LocalDateTime.now();
//
//    @Enumerated(EnumType.STRING)
//    @Column(name = "status")
//    private CandidateStatus status = CandidateStatus.SELECTED;
//
//    public enum CandidateStatus {
//        SELECTED, PROCESSING, COMPLETED, FAILED
//    }
//
//    public SettlementBatchCandidate() {
//    }
//
//    public SettlementBatchCandidate(Long batchId, String vendorTxId, BigDecimal expectedAmount,
//                                    BigDecimal expectedFee, BigDecimal expectedNet) {
//        this.batchId = batchId;
//        this.vendorTxId = vendorTxId;
//        this.expectedAmount = expectedAmount;
//        this.expectedFee = expectedFee;
//        this.expectedNet = expectedNet;
//        this.selectedAt = LocalDateTime.now();
//        this.status = CandidateStatus.SELECTED;
//    }
//
//    // Getters and setters will be generated by IntelliJ
//
//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    public Long getBatchId() {
//        return batchId;
//    }
//
//    public void setBatchId(Long batchId) {
//        this.batchId = batchId;
//    }
//
//    public String getVendorTxId() {
//        return vendorTxId;
//    }
//
//    public void setVendorTxId(String vendorTxId) {
//        this.vendorTxId = vendorTxId;
//    }
//
//    public BigDecimal getExpectedAmount() {
//        return expectedAmount;
//    }
//
//    public void setExpectedAmount(BigDecimal expectedAmount) {
//        this.expectedAmount = expectedAmount;
//    }
//
//    public BigDecimal getExpectedFee() {
//        return expectedFee;
//    }
//
//    public void setExpectedFee(BigDecimal expectedFee) {
//        this.expectedFee = expectedFee;
//    }
//
//    public BigDecimal getExpectedNet() {
//        return expectedNet;
//    }
//
//    public void setExpectedNet(BigDecimal expectedNet) {
//        this.expectedNet = expectedNet;
//    }
//
//    public LocalDateTime getSelectedAt() {
//        return selectedAt;
//    }
//
//    public void setSelectedAt(LocalDateTime selectedAt) {
//        this.selectedAt = selectedAt;
//    }
//
//    public CandidateStatus getStatus() {
//        return status;
//    }
//
//    public void setStatus(CandidateStatus status) {
//        this.status = status;
//    }
//}