package com.project2.ism.DTO.TempDTOs;

import java.math.BigDecimal;

public class FranchiseMerchantOption {

    private Long merchantId;
    private String businessName;
    private String contactPerson;
    private int availableTransactions;
    private BigDecimal totalAmount;

    public FranchiseMerchantOption() {
    }

    public FranchiseMerchantOption(Long merchantId, String businessName, String contactPerson,
                                   int availableTransactions, BigDecimal totalAmount) {
        this.merchantId = merchantId;
        this.businessName = businessName;
        this.contactPerson = contactPerson;
        this.availableTransactions = availableTransactions;
        this.totalAmount = totalAmount;
    }

    // Getters and setters will be generated by IntelliJ

    public Long getMerchantId() {
        return merchantId;
    }

    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    public String getBusinessName() {
        return businessName;
    }

    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    public String getContactPerson() {
        return contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    public int getAvailableTransactions() {
        return availableTransactions;
    }

    public void setAvailableTransactions(int availableTransactions) {
        this.availableTransactions = availableTransactions;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
}