package com.project2.ism.DTO.TempDTOs;

import com.project2.ism.Model.FranchiseSettlementBatch;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class FranchiseBatchResponse {

    private Long batchId;
    private Long franchiseId;
    private String cycleKey;
    private String status;
    private Integer totalMerchants;
    private Integer completedMerchants;
    private Integer failedMerchants;
    private Integer totalTransactions;
    private Integer processedTransactions;
    private BigDecimal totalFranchiseCommission;
    private LocalDateTime createdAt;
    private String createdBy;
    private LocalDateTime processingStartedAt;
    private LocalDateTime processingCompletedAt;
    private String errorMessage;

    public FranchiseBatchResponse() {
    }

    public FranchiseBatchResponse(FranchiseSettlementBatch batch) {
        this.batchId = batch.getId();
        this.franchiseId = batch.getFranchiseId();
        this.cycleKey = batch.getCycleKey();
        this.status = batch.getStatus().name();
        this.totalMerchants = batch.getTotalMerchants();
        this.completedMerchants = batch.getCompletedMerchants();
        this.failedMerchants = batch.getFailedMerchants();
        this.totalTransactions = batch.getTotalTransactions();
        this.processedTransactions = batch.getProcessedTransactions();
        this.totalFranchiseCommission = batch.getTotalFranchiseCommission();
        this.createdAt = batch.getCreatedAt();
        this.createdBy = batch.getCreatedBy();
        this.processingStartedAt = batch.getProcessingStartedAt();
        this.processingCompletedAt = batch.getProcessingCompletedAt();
        this.errorMessage = batch.getErrorMessage();
    }

    // Getters and setters will be generated by IntelliJ

    public Long getBatchId() {
        return batchId;
    }

    public void setBatchId(Long batchId) {
        this.batchId = batchId;
    }

    public Long getFranchiseId() {
        return franchiseId;
    }

    public void setFranchiseId(Long franchiseId) {
        this.franchiseId = franchiseId;
    }

    public String getCycleKey() {
        return cycleKey;
    }

    public void setCycleKey(String cycleKey) {
        this.cycleKey = cycleKey;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getTotalMerchants() {
        return totalMerchants;
    }

    public void setTotalMerchants(Integer totalMerchants) {
        this.totalMerchants = totalMerchants;
    }

    public Integer getCompletedMerchants() {
        return completedMerchants;
    }

    public void setCompletedMerchants(Integer completedMerchants) {
        this.completedMerchants = completedMerchants;
    }

    public Integer getFailedMerchants() {
        return failedMerchants;
    }

    public void setFailedMerchants(Integer failedMerchants) {
        this.failedMerchants = failedMerchants;
    }

    public Integer getTotalTransactions() {
        return totalTransactions;
    }

    public void setTotalTransactions(Integer totalTransactions) {
        this.totalTransactions = totalTransactions;
    }

    public Integer getProcessedTransactions() {
        return processedTransactions;
    }

    public void setProcessedTransactions(Integer processedTransactions) {
        this.processedTransactions = processedTransactions;
    }

    public BigDecimal getTotalFranchiseCommission() {
        return totalFranchiseCommission;
    }

    public void setTotalFranchiseCommission(BigDecimal totalFranchiseCommission) {
        this.totalFranchiseCommission = totalFranchiseCommission;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getProcessingStartedAt() {
        return processingStartedAt;
    }

    public void setProcessingStartedAt(LocalDateTime processingStartedAt) {
        this.processingStartedAt = processingStartedAt;
    }

    public LocalDateTime getProcessingCompletedAt() {
        return processingCompletedAt;
    }

    public void setProcessingCompletedAt(LocalDateTime processingCompletedAt) {
        this.processingCompletedAt = processingCompletedAt;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}