//package com.project2.ism.DTO.TempDTOs;
//
//import java.util.List;
//
//public class SelectiveFranchiseBatchRequest {
//
//    private String cycleKey;
//    private List<Long> selectedMerchantIds;
//    private String createdBy;
//
//    public SelectiveFranchiseBatchRequest() {
//    }
//
//    public SelectiveFranchiseBatchRequest(String cycleKey, List<Long> selectedMerchantIds, String createdBy) {
//        this.cycleKey = cycleKey;
//        this.selectedMerchantIds = selectedMerchantIds;
//        this.createdBy = createdBy;
//    }
//
//    // Getters and setters will be generated by IntelliJ
//
//    public String getCycleKey() {
//        return cycleKey;
//    }
//
//    public void setCycleKey(String cycleKey) {
//        this.cycleKey = cycleKey;
//    }
//
//    public List<Long> getSelectedMerchantIds() {
//        return selectedMerchantIds;
//    }
//
//    public void setSelectedMerchantIds(List<Long> selectedMerchantIds) {
//        this.selectedMerchantIds = selectedMerchantIds;
//    }
//
//    public String getCreatedBy() {
//        return createdBy;
//    }
//
//    public void setCreatedBy(String createdBy) {
//        this.createdBy = createdBy;
//    }
//}