// inventoryData.js - Sample data for inventory management
export const inventoryData = [
  {
    id: 1,
    type: 'inward',
    date: '2024-08-10',
    invoiceNumber: 'INV-2024-001',
    deliveryNumber: null,
    vendorId: 'VEN001',
    vendorName: 'HDFC Bank',
    customerId: null,
    customerName: null,
    productId: 'POS001',
    productName: 'HDFC POS Terminal',
    productType: 'pos_machine',
    quantity: 10,
    unitPrice: 15000,
    totalAmount: 150000,
    status: 'received',
    condition: 'new',
    batchNumber: 'BATCH001',
    warrantyPeriod: 24,
    serialNumbers: [
      { id: 1, MID: 'MID123456', SID: 'SID789012', TID: 'TID345678', VpID: 'VPA901234' },
      { id: 2, MID: 'MID123457', SID: 'SID789013', TID: 'TID345679', VpID: 'VPA901235' },
      { id: 3, MID: 'MID123458', SID: 'SID789014', TID: 'TID345680', VpID: 'VPA901236' }
    ],
    receivedBy: 'Admin User',
    dispatchedBy: null,
    remarks: 'New stock received from HDFC'
  },
  {
    id: 2,
    type: 'outward',
    date: '2024-08-11',
    invoiceNumber: null,
    deliveryNumber: 'DEL-2024-001',
    vendorId: null,
    vendorName: null,
    customerId: 'CUS001',
    customerName: 'Mumbai Franchise',
    productId: 'POS001',
    productName: 'HDFC POS Terminal',
    productType: 'pos_machine',
    quantity: 5,
    unitPrice: 15000,
    totalAmount: 75000,
    status: 'dispatched',
    condition: 'new',
    batchNumber: 'BATCH001',
    warrantyPeriod: 24,
    serialNumbers: [
      { id: 1, MID: 'MID123456', SID: 'SID789012', TID: 'TID345678', VpID: 'VPA901234' },
      { id: 2, MID: 'MID123457', SID: 'SID789013', TID: 'TID345679', VpID: 'VPA901235' }
    ],
    receivedBy: null,
    dispatchedBy: 'Admin User',
    deliveryAddress: '123 Main Street, Mumbai, Maharashtra',
    contactPerson: 'Rahul Sharma',
    contactNumber: '+91 9876543210',
    deliveryMethod: 'courier',
    trackingNumber: 'TRK123456789',
    expectedDelivery: '2024-08-15',
    remarks: 'Dispatched to Mumbai franchise'
  },
  {
    id: 3,
    type: 'inward',
    date: '2024-08-09',
    invoiceNumber: 'INV-2024-002',
    deliveryNumber: null,
    vendorId: 'VEN002',
    vendorName: 'ICICI Bank',
    customerId: null,
    customerName: null,
    productId: 'QR001',
    productName: 'ICICI QR Scanner',
    productType: 'qr_scanner',
    quantity: 15,
    unitPrice: 2500,
    totalAmount: 37500,
    status: 'received',
    condition: 'new',
    batchNumber: 'BATCH002',
    warrantyPeriod: 12,
    serialNumbers: [
      { id: 1, MID: 'MID654321', SID: 'SID210987', TID: 'TID876543', VpID: 'VPA432109' },
      { id: 2, MID: 'MID654322', SID: 'SID210988', TID: 'TID876544', VpID: 'VPA432110' }
    ],
    receivedBy: 'Inventory Manager',
    dispatchedBy: null,
    remarks: 'QR Scanners for retail merchants'
  },
  {
    id: 4,
    type: 'outward',
    date: '2024-08-12',
    invoiceNumber: null,
    deliveryNumber: 'DEL-2024-002',
    vendorId: null,
    vendorName: null,
    customerId: 'CUS002',
    customerName: 'Delhi Direct Merchant',
    productId: 'CR001',
    productName: 'Universal Card Reader',
    productType: 'card_reader',
    quantity: 3,
    unitPrice: 3500,
    totalAmount: 10500,
    status: 'in_transit',
    condition: 'new',
    batchNumber: 'BATCH003',
    warrantyPeriod: 18,
    serialNumbers: [
      { id: 1, MID: 'MID111111', SID: 'SID222222', TID: 'TID333333', VpID: 'VPA444444' }
    ],
    receivedBy: null,
    dispatchedBy: 'Dispatch Team',
    deliveryAddress: '456 Business Park, Delhi',
    contactPerson: 'Amit Kumar',
    contactNumber: '+91 9123456789',
    deliveryMethod: 'direct_delivery',
    trackingNumber: 'TRK987654321',
    expectedDelivery: '2024-08-14',
    remarks: 'Direct merchant delivery'
  },
  {
    id: 5,
    type: 'inward',
    date: '2024-08-08',
    invoiceNumber: 'INV-2024-003',
    deliveryNumber: null,
    vendorId: 'VEN003',
    vendorName: 'SBI Bank',
    customerId: null,
    customerName: null,
    productId: 'PR001',
    productName: 'Thermal Printer 80mm',
    productType: 'printer',
    quantity: 8,
    unitPrice: 4500,
    totalAmount: 36000,
    status: 'received',
    condition: 'new',
    batchNumber: 'BATCH004',
    warrantyPeriod: 12,
    serialNumbers: [
      { id: 1, MID: 'MID999999', SID: 'SID888888', TID: 'TID777777', VpID: 'VPA666666' }
    ],
    receivedBy: 'Warehouse Team',
    dispatchedBy: null,
    remarks: 'Thermal printers for receipt generation'
  },
  {
    id: 6,
    type: 'outward',
    date: '2024-08-13',
    invoiceNumber: null,
    deliveryNumber: 'DEL-2024-003',
    vendorId: null,
    vendorName: null,
    customerId: 'CUS003',
    customerName: 'Bangalore Franchise',
    productId: 'ACC001',
    productName: 'Power Adapter Set',
    productType: 'accessories',
    quantity: 20,
    unitPrice: 500,
    totalAmount: 10000,
    status: 'delivered',
    condition: 'new',
    batchNumber: 'BATCH005',
    warrantyPeriod: 6,
    serialNumbers: [],
    receivedBy: null,
    dispatchedBy: 'Admin User',
    deliveryAddress: '789 Tech Hub, Bangalore, Karnataka',
    contactPerson: 'Priya Nair',
    contactNumber: '+91 9876501234',
    deliveryMethod: 'logistics_partner',
    trackingNumber: 'TRK555666777',
    expectedDelivery: '2024-08-16',
    remarks: 'Accessory kit for new installations'
  }
];

export const getInventorySummary = () => {
  const summary = {
    totalInward: inventoryData.filter(item => item.type === 'inward').length,
    totalOutward: inventoryData.filter(item => item.type === 'outward').length,
    totalValue: inventoryData.reduce((sum, item) => sum + item.totalAmount, 0),
    recentTransactions: inventoryData
      .sort((a, b) => new Date(b.date) - new Date(a.date))
      .slice(0, 5)
  };
  
  return summary;
};