// Dummy merchant data
export const merchantData = [
    {
        id: 'MER001',
        name: 'Green Valley Foods',
        businessType: 'Grocery Store',
        contactPerson: 'Rajesh Kumar',
        email: 'rajesh@greenvalley.com',
        phone: '+91-9876543210',
        location: 'Mumbai, Maharashtra',
        products: 245,
        walletBalance: 15000,
        monthlyRevenue: 85000,
        status: 'active',
        joinedDate: '2024-01-15'
    },
    {
        id: 'MER002',
        name: 'Tech Solutions Hub',
        businessType: 'Electronics',
        contactPerson: 'Priya Sharma',
        email: 'priya@techsol.com',
        phone: '+91-9876543211',
        location: 'Bangalore, Karnataka',
        products: 180,
        walletBalance: 22000,
        monthlyRevenue: 120000,
        status: 'active',
        joinedDate: '2024-02-10'
    },
    {
        id: 'MER003',
        name: 'Fashion Forward',
        businessType: 'Clothing',
        contactPerson: 'Amit Patel',
        email: 'amit@fashionforward.com',
        phone: '+91-9876543212',
        location: 'Delhi, Delhi',
        products: 320,
        walletBalance: 8500,
        monthlyRevenue: 95000,
        status: 'pending',
        joinedDate: '2024-03-05'
    },
    {
        id: 'MER004',
        name: 'Home Essentials',
        businessType: 'Home & Garden',
        contactPerson: 'Sunita Singh',
        email: 'sunita@homeessentials.com',
        phone: '+91-9876543213',
        location: 'Pune, Maharashtra',
        products: 150,
        walletBalance: 12000,
        monthlyRevenue: 65000,
        status: 'active',
        joinedDate: '2024-01-20'
    },
    {
        id: 'MER005',
        name: 'Sports Arena',
        businessType: 'Sports & Fitness',
        contactPerson: 'Vikram Joshi',
        email: 'vikram@sportsarena.com',
        phone: '+91-9876543214',
        location: 'Chennai, Tamil Nadu',
        products: 95,
        walletBalance: 18500,
        monthlyRevenue: 75000,
        status: 'inactive',
        joinedDate: '2023-12-08'
    },
    {
        id: 'MER006',
        name: 'Book Paradise',
        businessType: 'Books & Media',
        contactPerson: 'Meera Reddy',
        email: 'meera@bookparadise.com',
        phone: '+91-9876543215',
        location: 'Hyderabad, Telangana',
        products: 420,
        walletBalance: 5500,
        monthlyRevenue: 45000,
        status: 'active',
        joinedDate: '2024-02-28'
    },
    {
        id: 'MER007',
        name: 'Auto Parts Plus',
        businessType: 'Automotive',
        contactPerson: 'Ravi Gupta',
        email: 'ravi@autopartsplus.com',
        phone: '+91-9876543216',
        location: 'Jaipur, Rajasthan',
        products: 280,
        walletBalance: 25000,
        monthlyRevenue: 110000,
        status: 'active',
        joinedDate: '2024-01-03'
    },
    {
        id: 'MER008',
        name: 'Beauty Bliss',
        businessType: 'Beauty & Personal Care',
        contactPerson: 'Kavita Agarwal',
        email: 'kavita@beautybliss.com',
        phone: '+91-9876543217',
        location: 'Kolkata, West Bengal',
        products: 165,
        walletBalance: 9200,
        monthlyRevenue: 58000,
        status: 'suspended',
        joinedDate: '2023-11-15'
    },
    {
        id: 'MER009',
        name: 'Pet Care Corner',
        businessType: 'Pet Supplies',
        contactPerson: 'Arjun Menon',
        email: 'arjun@petcare.com',
        phone: '+91-9876543218',
        location: 'Kochi, Kerala',
        products: 75,
        walletBalance: 14500,
        monthlyRevenue: 42000,
        status: 'active',
        joinedDate: '2024-03-12'
    },
    {
        id: 'MER010',
        name: 'Kitchen King',
        businessType: 'Kitchenware',
        contactPerson: 'Deepak Yadav',
        email: 'deepak@kitchenking.com',
        phone: '+91-9876543219',
        location: 'Lucknow, Uttar Pradesh',
        products: 210,
        walletBalance: 11800,
        monthlyRevenue: 72000,
        status: 'active',
        joinedDate: '2024-02-14'
    },
    {
        id: 'MER011',
        name: 'Toy World',
        businessType: 'Toys & Games',
        contactPerson: 'Sneha Kulkarni',
        email: 'sneha@toyworld.com',
        phone: '+91-9876543220',
        location: 'Nashik, Maharashtra',
        products: 135,
        walletBalance: 7800,
        monthlyRevenue: 38000,
        status: 'pending',
        joinedDate: '2024-03-20'
    },
    {
        id: 'MER012',
        name: 'Fresh Fruits Co',
        businessType: 'Food & Beverages',
        contactPerson: 'Suresh Iyer',
        email: 'suresh@freshfruits.com',
        phone: '+91-9876543221',
        location: 'Coimbatore, Tamil Nadu',
        products: 85,
        walletBalance: 16200,
        monthlyRevenue: 55000,
        status: 'active',
        joinedDate: '2024-01-08'
    },
    {
        id: 'MER013',
        name: 'Digital Dreams',
        businessType: 'Computer & Software',
        contactPerson: 'Ankit Jain',
        email: 'ankit@digitaldreams.com',
        phone: '+91-9876543222',
        location: 'Indore, Madhya Pradesh',
        products: 95,
        walletBalance: 21500,
        monthlyRevenue: 98000,
        status: 'active',
        joinedDate: '2024-02-22'
    }
];

export // Dummy merchant data
const approveMerchants = [
    {
        id: 'M001',
        businessName: 'Tech Solutions Retail',
        legalName: 'Tech Solutions Private Limited',
        franchiseName: 'Mumbai Central Tech Hub',
        franchiseId: 'F001',
        businessType: 'retail',
        gstNumber: '27ABCDE1234F1Z5',
        panNumber: 'ABCDE1234F',
        registrationNumber: 'REG123456789',
        businessAddress: '123, Tech Park, Andheri East, Mumbai - 400069',
        primaryContactName: 'Rahul Sharma',
        primaryContactMobile: '+91-9876543210',
        primaryContactEmail: 'rahul@techsolutions.com',
        alternateContactMobile: '+91-9876543211',
        landlineNumber: '022-12345678',
        whatsappNumber: '+91-9876543210',
        bankName: 'HDFC Bank',
        accountHolderName: 'Tech Solutions Pvt Ltd',
        accountNumber: '12345678901234',
        ifscCode: 'HDFC0001234',
        branchName: 'Andheri East Branch',
        accountType: 'current',
        status: 'pending',
        submittedDate: '2024-08-01',
        documents: {
            panCardDocument: 'pan_tech_solutions.pdf',
            gstCertificate: 'gst_tech_solutions.pdf',
            addressProof: 'address_tech_solutions.pdf',
            bankProof: 'bank_tech_solutions.pdf'
        }
    },
    {
        id: 'M002',
        businessName: 'Golden Spoon Restaurant',
        legalName: 'Golden Spoon Foods LLP',
        franchiseName: 'Delhi Food Court Network',
        franchiseId: 'F002',
        businessType: 'restaurant',
        gstNumber: '07ABCDE5678G1Z9',
        panNumber: 'ABCDE5678G',
        registrationNumber: 'REG987654321',
        businessAddress: '456, Connaught Place, New Delhi - 110001',
        primaryContactName: 'Priya Patel',
        primaryContactMobile: '+91-9876543212',
        primaryContactEmail: 'priya@goldenspoon.com',
        alternateContactMobile: '+91-9876543213',
        landlineNumber: '011-87654321',
        whatsappNumber: '+91-9876543212',
        bankName: 'ICICI Bank',
        accountHolderName: 'Golden Spoon Foods LLP',
        accountNumber: '98765432101234',
        ifscCode: 'ICIC0005678',
        branchName: 'Connaught Place Branch',
        accountType: 'current',
        status: 'approved',
        submittedDate: '2024-07-28',
        approvedDate: '2024-08-02',
        documents: {
            panCardDocument: 'pan_golden_spoon.pdf',
            gstCertificate: 'gst_golden_spoon.pdf',
            addressProof: 'address_golden_spoon.pdf',
            bankProof: 'bank_golden_spoon.pdf'
        }
    },
    {
        id: 'M003',
        businessName: 'Quick Fix Services',
        legalName: 'Quick Fix Solutions India Pvt Ltd',
        franchiseName: 'Bangalore Service Hub',
        franchiseId: 'F003',
        businessType: 'services',
        gstNumber: '29ABCDE9876H1Z3',
        panNumber: 'ABCDE9876H',
        registrationNumber: 'REG456789123',
        businessAddress: '789, Brigade Road, Bangalore - 560025',
        primaryContactName: 'Amit Kumar',
        primaryContactMobile: '+91-9876543214',
        primaryContactEmail: 'amit@quickfix.com',
        alternateContactMobile: '+91-9876543215',
        landlineNumber: '080-12345678',
        whatsappNumber: '+91-9876543214',
        bankName: 'SBI Bank',
        accountHolderName: 'Quick Fix Solutions India Pvt Ltd',
        accountNumber: '45678901234567',
        ifscCode: 'SBIN0009876',
        branchName: 'Brigade Road Branch',
        accountType: 'current',
        status: 'rejected',
        submittedDate: '2024-07-25',
        rejectedDate: '2024-07-30',
        rejectionReason: 'Invalid GST certificate',
        documents: {
            panCardDocument: 'pan_quick_fix.pdf',
            gstCertificate: 'gst_quick_fix.pdf',
            addressProof: 'address_quick_fix.pdf',
            bankProof: 'bank_quick_fix.pdf'
        }
    },
    {
        id: 'M004',
        businessName: 'Super Grocery Store',
        legalName: 'Super Grocery Mart Pvt Ltd',
        franchiseName: 'Chennai Retail Network',
        franchiseId: 'F004',
        businessType: 'grocery',
        gstNumber: '33ABCDE4567I1Z7',
        panNumber: 'ABCDE4567I',
        registrationNumber: 'REG789123456',
        businessAddress: '321, Anna Nagar, Chennai - 600040',
        primaryContactName: 'Lakshmi Iyer',
        primaryContactMobile: '+91-9876543216',
        primaryContactEmail: 'lakshmi@supergrocery.com',
        alternateContactMobile: '+91-9876543217',
        landlineNumber: '044-87654321',
        whatsappNumber: '+91-9876543216',
        bankName: 'Axis Bank',
        accountHolderName: 'Super Grocery Mart Pvt Ltd',
        accountNumber: '78901234567890',
        ifscCode: 'UTIB0004567',
        branchName: 'Anna Nagar Branch',
        accountType: 'current',
        status: 'pending',
        submittedDate: '2024-08-03',
        documents: {
            panCardDocument: 'pan_super_grocery.pdf',
            gstCertificate: 'gst_super_grocery.pdf',
            addressProof: 'address_super_grocery.pdf',
            bankProof: 'bank_super_grocery.pdf'
        }
    },
    {
        id: 'M005',
        businessName: 'City Pharmacy Plus',
        legalName: 'City Pharmacy Plus Limited',
        franchiseName: 'Hyderabad Healthcare Network',
        franchiseId: 'F005',
        businessType: 'pharmacy',
        gstNumber: '36ABCDE7890J1Z1',
        panNumber: 'ABCDE7890J',
        registrationNumber: 'REG234567890',
        businessAddress: '654, Jubilee Hills, Hyderabad - 500033',
        primaryContactName: 'Dr. Rajesh Reddy',
        primaryContactMobile: '+91-9876543218',
        primaryContactEmail: 'rajesh@citypharmacy.com',
        alternateContactMobile: '+91-9876543219',
        landlineNumber: '040-12345678',
        whatsappNumber: '+91-9876543218',
        bankName: 'Kotak Bank',
        accountHolderName: 'City Pharmacy Plus Limited',
        accountNumber: '12309845671234',
        ifscCode: 'KKBK0007890',
        branchName: 'Jubilee Hills Branch',
        accountType: 'current',
        status: 'pending',
        submittedDate: '2024-08-04',
        documents: {
            panCardDocument: 'pan_city_pharmacy.pdf',
            gstCertificate: 'gst_city_pharmacy.pdf',
            addressProof: 'address_city_pharmacy.pdf',
            bankProof: 'bank_city_pharmacy.pdf'
        }
    }
];