package com.project2.ism.Model.Product;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.project2.ism.Model.Product.Product;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;

@Entity
@Table(name = "product_specifications")
public class ProductSpecification {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "Specification key is required")
    @Column(name = "spec_key", nullable = false, length = 100)
    private String key;

    @NotBlank(message = "Specification value is required")
    @Column(name = "spec_value", nullable = false, length = 255)
    private String value;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    @JsonBackReference
    private Product product;

    // Default constructor
    public ProductSpecification() {}

    // Constructor
    public ProductSpecification(String key, String value, Product product) {
        this.key = key;
        this.value = value;
        this.product = product;
    }

    // Getters and setters will be generated by IntelliJ

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }
}
